spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/receipt_repository
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
server:
  port: 8081